language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: "N7EenUcspE/pyC1I+TVLowRIBKPylRC6Jlk/DP4u5GAqIkrLqeZPvTjrWBIMvCkZ2B2dPtUZ5IbbxRMTZCTOQxzlcOL4hbJyzsrRJsskya+Mg9oAFYrZJ6D77AZaQ8iwLgGsOBJsTCyBp9iTBiB3x3KZYUwaMPw3SScVrbNOgzk="
sudo: false
jobs:
  include:
    - stage: docs
      script: (cd docs/source && make html)
    - stage: deploy
      script:
        - curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
        - echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./conda-recipe --old-build-string --channel=main --org=csdms --token=-

before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels csdms
- conda config --add channels csdms-stack
- conda config --add channels conda-forge
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client sphinx
- conda update -n root conda-build -c defaults
script:
- conda build ./conda-recipe --no-test --old-build-string
- conda install pymt nose coverage --use-local
- nosetests --detailed-errors --exclude=examples --with-doctest --with-coverage --cover-package=pymt --verbosity=2 pymt
after_success:
- |
  if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    conda install -q coverage coveralls
    coveralls --verbose
  fi
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./conda-recipe --old-build-string --channel=dev --org=csdms --token=-
