language: generic
os:
- linux
- osx
env:
  matrix:
  - PYTHON="3.8"
  - PYTHON="3.7"
  - PYTHON="3.6"
  global:
    - secure: "N7EenUcspE/pyC1I+TVLowRIBKPylRC6Jlk/DP4u5GAqIkrLqeZPvTjrWBIMvCkZ2B2dPtUZ5IbbxRMTZCTOQxzlcOL4hbJyzsrRJsskya+Mg9oAFYrZJ6D77AZaQ8iwLgGsOBJsTCyBp9iTBiB3x3KZYUwaMPw3SScVrbNOgzk="
jobs:
  include:
  - stage: lint
    os: linux
    script:
    - pip install flake8
    - make lint
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > $HOME/miniconda.sh
  else
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > $HOME/miniconda.sh
  fi
- bash $HOME/miniconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- conda init bash
- hash -r
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    source $HOME/.bash_profile
  else
    source $HOME/.bashrc
  fi
- conda config --set always_yes yes --set changeps1 no
- conda create -n _testing python=$PYTHON
- conda activate _testing
- conda info -a && conda list
install:
- pip install -e .
- conda install esmpy udunits2 -c conda-forge
script:
- pip install -r requirements-testing.txt
- pytest --cov=pymt --cov-report=xml:$(pwd)/coverage.xml -vvv
after_success: coveralls
