environment:

  matrix:
    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
      CONDA_ENV: py37-windows

    - TARGET_ARCH: x64
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      CONDA_ENV: py36-windows

platform:
  - x64

os: Previous Visual Studio 2015

init:
  - "ECHO %CONDA_INSTALL_LOCN% %CONDA_PY% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda config --set always_yes yes
  - cmd: conda update conda
  - cmd: conda config --append channels conda-forge
  - cmd: conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml;
  - cmd: conda activate test_env
  - cmd: conda info -a && conda list
  - cmd: python setup.py install


build: false

test_script:
  - pytest
