environment:

  matrix:

    - PYTHON: "3.7"
      MINICONDA: C:\\Miniconda37-x64

    - PYTHON: "3.6"
      MINICONDA: C:\\Miniconda36-x64

platform:
  - x64

# os: Previous Visual Studio 2015

init:
  - "ECHO %PYTHON% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda config --set always_yes yes
  - cmd: conda install udunits2 -c conda-forge
  - cmd: conda list
  - cmd: python --version

build: false

test_script:
  - cmd: pip install cython numpy
  - cmd: pip install -r requirements-testing.txt
  - cmd: pip install -e .
  - cmd: pytest -vvv
